import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { db, TABLE_NAMES } from './db';
import { applyExcelImport, inspectExcelImport, type ExcelImportPreview } from './io';
import { batchCurrentCount, enterprisePnl, feedStock, type FarmData } from './calculations';
import type { AdvancedData } from './advanced';
import { localDate, type AppSetting, type Worker } from './types';

export type CoreData=FarmData&AdvancedData&{workers:Worker[];settings:AppSetting[]};
type Action=(fn:()=>Promise<unknown>,message?:string)=>Promise<boolean>;
const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0),today=()=>localDate(),future=(days:number)=>localDate(new Date(Date.now()+days*86400000));
const Card=({children,className=''}:{children:ReactNode,className?:string})=><section className={`card ${className}`}>{children}</section>;
async function pinDigest(pin:string,salt:string){const bytes=new TextEncoder().encode(`${salt}:${pin}`),digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('')}

export function coreArchiveBlocker(kind:'enterprises'|'workers'|'expenses'|'income'|'labour'|'plots'|'rotations',recordId:string,data:CoreData){if(kind==='enterprises'){const linked=data.expenses.some(x=>x.enterpriseId===recordId||x.allocations?.some(a=>a.enterpriseId===recordId))||data.otherIncome.some(x=>x.enterpriseId===recordId)||data.labourLogs.some(x=>x.allocations.some(a=>a.enterpriseId===recordId))||data.batches.some(x=>x.enterpriseId===recordId)||data.feedPurchases.some(x=>x.allocations.some(a=>a.enterpriseId===recordId))||data.feedHarvests.some(x=>x.allocations.some(a=>a.enterpriseId===recordId))||data.feedConsumption.some(x=>x.enterpriseId===recordId)||data.plotCycles.some(x=>x.enterpriseId===recordId)||data.herds.some(x=>x.enterpriseId===recordId)||data.cropCycles.some(x=>x.enterpriseId===recordId)||data.eggSales.some(x=>x.enterpriseId===recordId)||data.birdSales.some(x=>x.enterpriseId===recordId)||data.herdSales.some(x=>x.enterpriseId===recordId)||data.cropSales.some(x=>x.enterpriseId===recordId);if(linked)return 'This enterprise has linked history. Make it inactive in the Enterprise registry instead.'}if(kind==='workers'&&data.labourLogs.some(x=>x.workerId===recordId))return 'This worker has labour history. Make the worker inactive instead.';if(kind==='plots'&&(data.plotCycles.some(x=>x.plotId===recordId)||data.cropCycles.some(x=>x.plotId===recordId)))return 'This plot has rotation or crop history and cannot be archived.';if(kind==='rotations'&&data.feedUnits.some(x=>x.plotCycleId===recordId))return 'This rotation is linked to a feed production unit and cannot be archived.';return ''}

export function PinGate({settings,children}:{settings:AppSetting[],children:ReactNode}){const hash=settings.find(x=>x.key==='pinHash')?.value,salt=settings.find(x=>x.key==='pinSalt')?.value||'', [unlocked,setUnlocked]=useState(!hash),[error,setError]=useState('');if(unlocked||!hash)return <>{children}</>;return <div className="lockScreen"><Card><div className="brandmark">FM</div><h2>Farm Manager is locked</h2><p className="note">Enter the farm PIN. Your records remain on this device.</p><form onSubmit={async e=>{e.preventDefault();const pin=String(new FormData(e.currentTarget).get('pin')||'');if(await pinDigest(pin,salt)===hash){setUnlocked(true);setError('')}else setError('Incorrect PIN.')}}><label>PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4,8}" autoFocus required/></label>{error&&<span className="negative">{error}</span>}<button className="primary">Unlock</button></form></Card></div>}

export function PinSettings({data,act}:{data:CoreData,act:Action}){const enabled=Boolean(data.settings.find(x=>x.key==='pinHash')?.value);return <Card><h2>App PIN</h2><p className="note">This locks the app interface on startup. It does not encrypt IndexedDB or backup files.</p>{enabled?<button className="danger" onClick={()=>act(()=>db.settings.bulkDelete(['pinHash','pinSalt']),'PIN removed')}>Remove PIN</button>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),pin=String(f.get('pin')||''),confirmPin=String(f.get('confirmPin')||'');act(async()=>{if(!/^\d{4,8}$/.test(pin))throw Error('Use a 4–8 digit PIN.');if(pin!==confirmPin)throw Error('PIN entries do not match.');const salt=crypto.randomUUID();await db.settings.bulkPut([{key:'pinSalt',value:salt},{key:'pinHash',value:await pinDigest(pin,salt)}])},'PIN enabled')}}><label>New 4–8 digit PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4,8}" required/></label><label>Confirm PIN<input name="confirmPin" type="password" inputMode="numeric" pattern="[0-9]{4,8}" required/></label><button className="primary">Enable PIN</button></form>}</Card>}

export function ExcelImportPanel({act}:{act:Action}){const [preview,setPreview]=useState<ExcelImportPreview|null>(null),[fileName,setFileName]=useState('');return <Card><h2>Import Excel workbook</h2><p className="note">Import a Farm Manager workbook after editing it in Excel. Existing IDs are updated; new IDs are added. Nothing is written until validation passes.</p><label className="restore">Choose Excel workbook<input type="file" accept=".xlsx,.xls" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setFileName(file.name);try{setPreview(await inspectExcelImport(file))}catch(error){setPreview({tables:{},counts:{},warnings:[],errors:[error instanceof Error?error.message:'Could not read workbook.']})}}}/></label>{preview&&<div className="importPreview"><b>{fileName}</b><p>{Object.entries(preview.counts).map(([name,count])=>`${name}: ${count}`).join(' · ')||'No importable records'}</p>{preview.errors.map((x,i)=><div className="validationError" key={i}>⚠ {x}</div>)}{!preview.errors.length&&<><div className="validationOk">✓ Workbook validation passed</div><button className="primary" onClick={()=>act(()=>applyExcelImport(preview),'Excel records imported')}>Import records</button></>}</div>}</Card>}

type ArchivedRecord={table:string;record:Record<string,unknown>};
const archivedTitle=(record:Record<string,unknown>)=>String(record.name||record.category||record.source||record.task||record.cropOrUse||record.commodity||record.type||record.date||record.id);
function ArchivedRecords({act}:{act:Action}){const [rows,setRows]=useState<ArchivedRecord[]>([]),load=async()=>{const tables=TABLE_NAMES.filter(name=>name!=='settings');const found=(await Promise.all(tables.map(async table=>(await db.table(table).toArray() as Array<Record<string,unknown>>).filter(record=>Boolean(record.deletedAt)).map(record=>({table,record}))))).flat();setRows(found.sort((a,b)=>String(b.record.deletedAt).localeCompare(String(a.record.deletedAt))))};useEffect(()=>{void load()},[act]);const restore=(row:ArchivedRecord)=>act(async()=>{await db.table(row.table).update(String(row.record.id),{deletedAt:undefined,updatedAt:new Date().toISOString()});await load()},'Archived record restored');return <Card><div className="sectionHead"><div><small>RESTORABLE HISTORY</small><h2>Archived records</h2></div><span className="pill">{rows.length}</span></div><p className="note">Archive removes a record from working screens without erasing history. Restore returns it to the app. Permanent deletion is intentionally unavailable.</p>{rows.length?rows.map(row=><div className="record" key={`${row.table}:${String(row.record.id)}`}><span><b>{archivedTitle(row.record)}</b><small>{row.table} · archived {String(row.record.deletedAt).slice(0,10)}</small></span><button className="small" onClick={()=>restore(row)}>Restore</button></div>):<div className="empty">No archived records.</div>}</Card>}

export function CoreRecords({data,act}:{data:CoreData,act:Action}){const [kind,setKind]=useState<'enterprises'|'workers'|'expenses'|'income'|'labour'|'plots'|'rotations'>('enterprises');const table=kind==='income'?'otherIncome':kind==='labour'?'labourLogs':kind==='plots'?'landPlots':kind==='rotations'?'plotCycles':kind;const records=(kind==='enterprises'?data.enterprises:kind==='workers'?data.workers:kind==='expenses'?data.expenses:kind==='income'?data.otherIncome:kind==='labour'?data.labourLogs:kind==='plots'?data.landPlots:data.plotCycles) as Array<Record<string,unknown>>;const archive=(record:Record<string,unknown>)=>act(async()=>{const recordId=String(record.id);const blocker=coreArchiveBlocker(kind,recordId,data);if(blocker)throw Error(blocker);await db.table(table).update(recordId,{deletedAt:new Date().toISOString(),updatedAt:new Date().toISOString()})},'Core record archived');const title=(r:Record<string,unknown>)=>String(r.name||r.category||r.source||r.task||r.cropOrUse||r.date||r.id);return <><Card><div className="sectionHead"><div><small>SHARED HISTORY</small><h2>Corrections &amp; archive</h2></div><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="enterprises">Enterprises</option><option value="workers">Workers</option><option value="expenses">Expenses</option><option value="income">Other income</option><option value="labour">Labour</option><option value="plots">Land plots</option><option value="rotations">Plot rotations</option></select></div><p className="note">Archive an incorrect transaction and enter its corrected replacement in the relevant screen. Linked enterprises and workers must be made inactive so their historical reports remain valid.</p>{records.map(record=><div className="record" key={String(record.id)}><span><b>{title(record)}</b><small>{String(record.date||record.type||record.wageType||'')}</small></span><button className="danger small" onClick={()=>archive(record)}>Archive</button></div>)}</Card><ArchivedRecords act={act}/></>}

type AlertItem={id:string;title:string;detail:string};
const settingNumber=(data:CoreData,key:string,fallback:number)=>{const value=Number(data.settings.find(x=>x.key===key)?.value);return Number.isFinite(value)?value:fallback};
const plusDays=(value:string,days:number)=>new Date(new Date(`${value}T00:00:00Z`).getTime()+days*86400000).toISOString().slice(0,10);
const safeJson=<T,>(value:string|undefined,fallback:T):T=>{try{return value?JSON.parse(value) as T:fallback}catch{return fallback}};

export function outstandingHealthReminders(data:CoreData,asOf=today()){
  const poultry=data.healthRecords.filter(record=>record.nextDueDate&&record.nextDueDate<=asOf&&data.batches.some(batch=>batch.id===record.batchId&&batch.active!==false)&&!data.healthRecords.some(later=>later.batchId===record.batchId&&later.type===record.type&&later.date>record.date&&later.date<=asOf));
  const herds=data.herdHealth.filter(record=>record.nextDueDate&&record.nextDueDate<=asOf&&data.herds.some(herd=>herd.id===record.herdId&&herd.active!==false)&&!data.herdHealth.some(later=>later.herdId===record.herdId&&later.type===record.type&&later.date>record.date&&later.date<=asOf));
  return {poultry,herds};
}

export function buildAlerts(data:CoreData,asOf=today()):AlertItem[]{
  const items:AlertItem[]=[],threeDays=new Date(new Date(`${asOf}T00:00:00Z`).getTime()-2*86400000).toISOString().slice(0,10),week=new Date(new Date(`${asOf}T00:00:00Z`).getTime()-6*86400000).toISOString().slice(0,10),deathThreshold=settingNumber(data,'mortalityDeathThreshold',3),percentThreshold=settingNumber(data,'mortalityPercentThreshold',2);
  const dueHealth=outstandingHealthReminders(data,asOf);
  dueHealth.poultry.forEach(x=>items.push({id:`phealth:${x.id}:${x.updatedAt}`,title:'Poultry health due',detail:`${x.type} · ${x.nextDueDate}`}));
  dueHealth.herds.forEach(x=>items.push({id:`hhealth:${x.id}:${x.updatedAt}`,title:'Herd health due',detail:`${x.type} · ${x.nextDueDate}`}));
  data.breedingEvents.filter(x=>x.followUpDate&&x.followUpDate<=asOf&&data.herds.some(herd=>herd.id===x.herdId&&herd.active!==false)).forEach(x=>items.push({id:`breeding:${x.id}:${x.updatedAt}`,title:'Kidding/lambing follow-up',detail:`${data.herds.find(h=>h.id===x.herdId)?.name||'Herd'} · ${x.followUpDate}`}));
  data.batches.filter(batch=>batch.active!==false).forEach(batch=>{const losses3=data.mortalities.filter(x=>x.batchId===batch.id&&x.date>=threeDays&&x.date<=asOf).reduce((v,x)=>v+x.countLost,0),losses7=data.mortalities.filter(x=>x.batchId===batch.id&&x.date>=week&&x.date<=asOf).reduce((v,x)=>v+x.countLost,0),entered=batch.initialCount+data.additions.filter(x=>x.batchId===batch.id&&x.date<=asOf).reduce((v,x)=>v+x.count,0);if(losses3>=deathThreshold||(entered>0&&losses7/entered*100>percentThreshold))items.push({id:`poultry-mortality:${batch.id}:${losses3}:${losses7}:${week}`,title:'Poultry mortality spike',detail:`${batch.name} · ${losses3} losses in 3 days, ${losses7} in 7 days`});if(batch.expectedLayStart&&batch.expectedLayStart<=asOf&&!data.eggProduction.some(x=>x.batchId===batch.id&&x.date<=asOf))items.push({id:`lay-start:${batch.id}:${batch.expectedLayStart}`,title:'Expected laying start reached',detail:`${batch.name} · ${batch.expectedLayStart}`});const ready=plusDays(batch.acquisitionDate,Math.max(0,(batch.targetMeatAgeDays||settingNumber(data,'targetMeatAgeDays',180))-batch.ageAtAcquisitionDays));if((batch.purpose==='meat'||batch.purpose==='dual')&&ready<=asOf&&batchCurrentCount(batch,data,asOf)>0)items.push({id:`meat-ready:${batch.id}:${ready}`,title:'Target meat age reached',detail:`${batch.name} · target date ${ready}`})});
  data.herds.filter(herd=>herd.active!==false).forEach(herd=>{const losses=data.herdMortalities.filter(x=>x.herdId===herd.id&&x.date>=week&&x.date<=asOf).reduce((v,x)=>v+x.countLost,0),entered=herd.initialCount+data.herdAdditions.filter(x=>x.herdId===herd.id&&x.date<=asOf).reduce((v,x)=>v+x.count,0);if(losses>=deathThreshold||(entered>0&&losses/entered*100>percentThreshold))items.push({id:`herd-mortality:${herd.id}:${losses}:${week}`,title:'Herd mortality spike',detail:`${herd.name} · ${losses} losses in 7 days`})});
  data.labourLogs.filter(x=>!x.paid&&x.date<=asOf).forEach(x=>items.push({id:`wage:${x.id}:${x.updatedAt}`,title:'Wage unpaid',detail:`${x.task} · ${money(x.amount)}`}));
  data.cropCycles.filter(x=>x.expectedHarvest&&x.expectedHarvest<=plusDays(asOf,7)&&x.status!=='complete').forEach(x=>items.push({id:`harvest:${x.id}:${x.updatedAt}`,title:'Harvest window',detail:`${x.crop} · ${x.expectedHarvest}`}));
  const reorderDays=settingNumber(data,'feedReorderDays',7);data.feedTypes.forEach(type=>{const stock=feedStock(type.id,data,asOf),used=data.feedConsumption.filter(x=>x.feedTypeId===type.id&&x.date>=week&&x.date<=asOf).reduce((v,x)=>v+x.quantity,0),daily=used/7,days=daily?stock/daily:Infinity;if(stock<=0||days<=reorderDays)items.push({id:`feed:${type.id}:${Math.floor(days*10)}`,title:stock<=0?'Feed out of stock':'Feed reorder due',detail:stock<=0?type.name:`${type.name} · approximately ${days.toFixed(1)} days remaining`})});
  return items;
}
export function AlertCenter({data,act}:{data:CoreData,act:Action}){const alerts=buildAlerts(data),snoozes=safeJson<Record<string,string>>(data.settings.find(x=>x.key==='alertSnoozes')?.value,{}),dismissed=safeJson<string[]>(data.settings.find(x=>x.key==='alertDismissed')?.value,[]),visible=alerts.filter(x=>(!snoozes[x.id]||snoozes[x.id]<=today())&&!dismissed.includes(x.id));const save=(key:string,value:unknown)=>act(()=>db.settings.put({key,value:JSON.stringify(value)}),'Alert preference saved');return <Card><div className="sectionHead"><div><small>FARM-WIDE</small><h2>Alert centre</h2></div><span className="pill">{visible.length} active</span></div>{visible.length?visible.map(x=><div className="record" key={x.id}><span><b>{x.title}</b><small>{x.detail}</small></span><span className="recordActions"><button onClick={()=>save('alertSnoozes',{...snoozes,[x.id]:future(7)})}>Snooze 7d</button><button className="danger small" onClick={()=>save('alertDismissed',[...dismissed,x.id])}>Dismiss</button></span></div>):<div className="empty">No active shared-core alerts.</div>}</Card>}

export function CoreTrends({data}:{data:CoreData}){const months=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const from=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`,end=new Date(d.getFullYear(),d.getMonth()+1,0),to=`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}`,values=data.enterprises.map(e=>enterprisePnl(e.id,data,{from,to}));return {label:d.toLocaleString('en-IN',{month:'short'}),revenue:values.reduce((v,x)=>v+x.revenue,0),cost:values.reduce((v,x)=>v+x.directCosts,0)}}),[data]),max=Math.max(1,...months.flatMap(x=>[x.revenue,x.cost]));return <Card><h2>Six-month consolidated trend</h2><div className="trendChart">{months.map(x=><div className="trendMonth" key={x.label}><div className="trendBars"><i className="revenueBar" style={{height:`${x.revenue/max*100}%`}} title={`Revenue ${money(x.revenue)}`}/><i className="costBar" style={{height:`${x.cost/max*100}%`}} title={`Cost ${money(x.cost)}`}/></div><small>{x.label}</small></div>)}</div><div className="trendLegend"><span>● Revenue</span><span>● Costs</span></div></Card>}
