import { cropMetrics, enterprisePnl, feedCostPerUnit, herdMetrics, type FarmData } from './calculations';
import type { CropHarvest, MarketPrice, WeatherLog } from './types';
import { localDate } from './types';

export type IntelligenceData=FarmData&{cropHarvests:CropHarvest[];marketPrices:MarketPrice[];weatherLogs:WeatherLog[]};
export const AGMARKNET_RESOURCE_ID='9ef84268-d588-465a-a308-a864a43d0070';
const same=(a:string,b:string)=>a.trim().toLowerCase()===b.trim().toLowerCase();
export const shouldReplaceWeather=(existing:WeatherLog|undefined,incomingSource:WeatherLog['source'])=>!existing||existing.source!=='manual'||incomingSource==='manual';
export function normalizedMarketPrice(row:MarketPrice,target:'kg'|'bunch'|'piece'){const unit=row.unit.toLowerCase().trim();if(target==='kg'){if(unit.includes('quintal')||unit==='100 kg'||unit==='100kg')return row.modalPrice/100;if(unit==='tonne'||unit==='metric ton'||unit==='mt')return row.modalPrice/1000;if(unit==='kg'||unit.includes('/kg'))return row.modalPrice}if(unit===target||unit===`${target}s`||unit.includes(`/${target}`))return row.modalPrice;return null}

export function normalizeApiDate(value:string){if(/^\d{2}\/\d{2}\/\d{4}$/.test(value)){const [day,month,year]=value.split('/');return `${year}-${month}-${day}`}return /^\d{4}-\d{2}-\d{2}$/.test(value)?value:''}
export type MarketApiRow=Omit<MarketPrice,'id'|'createdAt'|'updatedAt'|'deletedAt'>;
export function marketPriceFromApiRecord(record:Record<string,string>,requested:string,fallbackDate=localDate()):MarketApiRow|null{
  const pick=(...keys:string[])=>keys.map(key=>record[key]).find(value=>value!=null&&String(value).trim()!=='')||'',number=(value:string)=>Number(String(value).replace(/,/g,''));
  const minPrice=number(pick('min_price','Min_Price')),maxPrice=number(pick('max_price','Max_Price')),modalPrice=number(pick('modal_price','Modal_Price'));
  if(!Number.isFinite(minPrice)||!Number.isFinite(maxPrice)||!Number.isFinite(modalPrice)||minPrice<0||maxPrice<minPrice||modalPrice<minPrice||modalPrice>maxPrice||modalPrice<=0)return null;
  const arrival=number(pick('arrival_quantity','arrivals','Arrival_Quantity'));
  return {date:normalizeApiDate(pick('arrival_date','date','Arrival_Date'))||fallbackDate,commodity:String(pick('commodity','Commodity')||requested).trim(),variety:String(pick('variety','Variety')).trim(),market:String(pick('market','Market')||'Unknown market').trim(),minPrice,maxPrice,modalPrice,arrivalQuantity:Number.isFinite(arrival)&&arrival>0?arrival:undefined,unit:String(pick('unit','Unit')||'quintal').trim(),source:'data.gov.in'};
}

export type CommoditySignal={commodity:string;unit:'kg'|'bunch'|'piece';currentMarket:number;averageMarket:number;bestMarket:number;bestDate?:string;actualAverage:number;gapPercent:number;arrivalTrend:number;marketRows:number};
export function commoditySignals(data:IntelligenceData):CommoditySignal[]{const commodities=Array.from(new Set((data.cropCycles||[]).map(x=>x.crop)));return commodities.map(commodity=>{const cycles=(data.cropCycles||[]).filter(x=>same(x.crop,commodity)),cycleIds=new Set(cycles.map(x=>x.id)),sales=(data.cropSales||[]).filter(x=>cycleIds.has(x.cycleId)),harvests=data.cropHarvests.filter(x=>cycleIds.has(x.cycleId)),unit=(sales[0]?.unit||harvests[0]?.unit||'kg') as CommoditySignal['unit'],comparableSales=sales.filter(x=>x.unit===unit),rows=data.marketPrices.filter(x=>same(x.commodity,commodity)).map(row=>({row,value:normalizedMarketPrice(row,unit)})).filter((x):x is {row:MarketPrice;value:number}=>x.value!=null).sort((a,b)=>a.row.date.localeCompare(b.row.date)),recent=rows.slice(-30),current=recent.at(-1)?.value||0,average=recent.length?recent.reduce((v,x)=>v+x.value,0)/recent.length:0,best=recent.slice().sort((a,b)=>b.value-a.value)[0],saleQty=comparableSales.reduce((v,x)=>v+x.quantity,0),actual=saleQty?comparableSales.reduce((v,x)=>v+x.total,0)/saleQty:0,arrivals=recent.filter(x=>x.row.arrivalQuantity!=null),half=Math.floor(arrivals.length/2),first=arrivals.length>=2?arrivals.slice(0,half).reduce((v,x)=>v+(x.row.arrivalQuantity||0),0)/half:0,lastRows=arrivals.length>=2?arrivals.slice(half):[],last=lastRows.length?lastRows.reduce((v,x)=>v+(x.row.arrivalQuantity||0),0)/lastRows.length:0;return {commodity,unit,currentMarket:current,averageMarket:average,bestMarket:best?.value||0,bestDate:best?.row.date,actualAverage:actual,gapPercent:average&&actual?(actual-average)/average*100:0,arrivalTrend:first?(last-first)/first*100:0,marketRows:rows.length}})}

export type CropForecast={cycleId:string;crop:string;unit:'kg'|'bunch'|'piece';projectedYield:number;projectedRevenue:number;breakEvenPrice:number;confidence:'current-cycle'|'historical'|'insufficient';marketPrice:number};
export function cropForecasts(data:IntelligenceData):CropForecast[]{const signals=commoditySignals(data);return (data.cropCycles||[]).filter(x=>x.status!=='complete').map(cycle=>{const own=cropMetrics(cycle,data),historical=(data.cropCycles||[]).filter(x=>x.id!==cycle.id&&x.status==='complete'&&same(x.crop,cycle.crop)).map(x=>cropMetrics(x,data)).filter(x=>x.quantities[x.primaryUnit]>0),unit=own.primaryUnit,ownYield=own.quantities[unit],historicalPerAcre=historical.filter(x=>x.primaryUnit===unit).reduce((v,x)=>v+x.yieldPerAcre,0)/(historical.filter(x=>x.primaryUnit===unit).length||1),projectedYield=ownYield||historicalPerAcre*cycle.areaAcres,signal=signals.find(x=>same(x.commodity,cycle.crop)&&x.unit===unit),marketPrice=signal?.currentMarket||signal?.averageMarket||signal?.actualAverage||0;return {cycleId:cycle.id,crop:cycle.crop,unit,projectedYield,projectedRevenue:projectedYield*marketPrice,breakEvenPrice:projectedYield?own.cost/projectedYield:0,confidence:ownYield?'current-cycle':historicalPerAcre?'historical':'insufficient',marketPrice}})}

export function weatherWarnings(data:IntelligenceData,asOf=localDate()){const forecast=data.weatherLogs.filter(x=>x.forecast&&x.date>=asOf).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,7),warnings:string[]=[];if(!forecast.length)return ['No weather forecast is cached. Update weather when online or add a manual record.'];const rain=forecast.reduce((v,x)=>v+x.rainfallMm,0),hot=Math.max(...forecast.map(x=>x.tempMax)),humid=Math.max(...forecast.map(x=>x.humidityPercent));if(rain>=50)warnings.push(`${rain.toFixed(0)} mm rain forecast in 7 days: review harvest, drainage and spray timing.`);if(rain<5)warnings.push(`Only ${rain.toFixed(0)} mm rain forecast in 7 days: review irrigation.`);if(hot>=35)warnings.push(`Maximum temperature reaches ${hot.toFixed(1)}°C: review heat stress and irrigation.`);if(humid>=85)warnings.push(`Humidity reaches ${humid.toFixed(0)}%: monitor fungal disease risk.`);return warnings.length?warnings:['No threshold-based weather warnings for the next 7 days.']}

export function livestockBreakEven(data:IntelligenceData){return (data.herds||[]).map(herd=>{const m=herdMetrics(herd,data),gap=Math.max(0,m.cumulativeDirectCost-m.revenue),sales=(data.herdSales||[]).filter(x=>x.herdId===herd.id),quantity=sales.reduce((v,x)=>v+x.quantity,0),averagePrice=quantity?sales.reduce((v,x)=>v+x.total,0)/quantity:0;return {herdId:herd.id,name:herd.name,gap,averagePrice,unitsNeeded:averagePrice?gap/averagePrice:0,recovered:m.revenue>=m.cumulativeDirectCost}})}

export function wholeFarmInsights(data:IntelligenceData,from=`${new Date().getFullYear()}-01-01`,to=localDate()){const ranks=data.enterprises.map(e=>({enterprise:e,pnl:enterprisePnl(e.id,data,{from,to})})).sort((a,b)=>b.pnl.net-a.pnl.net),week=new Date(new Date(`${to}T00:00:00Z`).getTime()-6*86400000).toISOString().slice(0,10),mortality=data.mortalities.filter(x=>x.date>=week&&x.date<=to).reduce((v,x)=>v+x.countLost,0)+(data.herdMortalities||[]).filter(x=>x.date>=week&&x.date<=to).reduce((v,x)=>v+x.countLost,0),unpaid=data.labourLogs.filter(x=>!x.paid).reduce((v,x)=>v+x.amount,0),feedDrift=(()=>{const trends=(data.feedTypes||[]).flatMap(type=>{const rows=(data.feedPurchases||[]).filter(x=>x.feedTypeId===type.id).sort((a,b)=>a.date.localeCompare(b.date)),latest=rows.at(-1),previous=rows.at(-2);return latest?.quantity&&previous?.quantity?[{name:type.name,percent:(latest.totalCost/latest.quantity-previous.totalCost/previous.quantity)/(previous.totalCost/previous.quantity)*100}]:[]});return trends.sort((a,b)=>Math.abs(b.percent)-Math.abs(a.percent))[0]})();return {top:ranks[0],bottom:ranks.at(-1),mortality,unpaid,feedDrift}}
