import { type FormEvent, type ReactNode } from 'react';
import { db } from './db';
import { commoditySignals, cropForecasts, livestockBreakEven, weatherWarnings, wholeFarmInsights, type IntelligenceData } from './intelligence';
import { localDate, stamp, type AppSetting, type WeatherLog } from './types';

type InsightData=IntelligenceData&{settings:AppSetting[]};
type Action=(fn:()=>Promise<unknown>,message?:string)=>Promise<boolean>;
const Card=({children}:{children:ReactNode})=><section className="card">{children}</section>;
const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value||0),date=(value:string)=>value.split('-').reverse().join('-'),today=()=>localDate();

export function DecisionInsights({data}:{data:InsightData}){const summary=wholeFarmInsights(data),signals=commoditySignals(data);return <><div className="statgrid"><Card><small>TOP ENTERPRISE</small><strong>{summary.top?.enterprise.name||'—'}</strong><span>{money(summary.top?.pnl.net||0)} net</span></Card><Card><small>NEEDS ATTENTION</small><strong>{summary.bottom?.enterprise.name||'—'}</strong><span>{money(summary.bottom?.pnl.net||0)} net</span></Card><Card><small>UNPAID WAGES</small><strong>{money(summary.unpaid)}</strong><span>{summary.mortality} animal losses in 7 days</span></Card></div>{summary.feedDrift&&<Card><div className="sectionHead"><div><small>FEED COST SIGNAL</small><h2>{summary.feedDrift.name}</h2></div><span className={summary.feedDrift.percent>10?'pill bad':'pill'}>{summary.feedDrift.percent>=0?'+':''}{summary.feedDrift.percent.toFixed(1)}%</span></div><p className="note">Change between the two most recent purchase unit costs.</p></Card>}<Card><div className="sectionHead"><div><small>ACTUAL SALES VS MARKET</small><h2>Selling signals</h2></div><span className="pill">Last 30 market rows</span></div>{signals.length?<div className="table pnl"><div className="tr head"><span>Commodity</span><span>Farm price</span><span>Market</span><span>Gap</span><span>Best recent</span><span>Arrivals</span></div>{signals.map(x=><div className="tr" key={x.commodity}><span>{x.commodity}<small>{x.marketRows} comparable rows</small></span><span>{x.actualAverage?`${money(x.actualAverage)}/${x.unit}`:'—'}</span><span>{x.currentMarket?`${money(x.currentMarket)}/${x.unit}`:'—'}</span><span className={x.gapPercent>=0?'positive':'negative'}>{x.actualAverage&&x.averageMarket?`${x.gapPercent>=0?'+':''}${x.gapPercent.toFixed(1)}%`:'—'}</span><span>{x.bestMarket?`${money(x.bestMarket)} · ${date(x.bestDate!)}`:'—'}</span><span>{x.arrivalTrend?`${x.arrivalTrend>=0?'+':''}${x.arrivalTrend.toFixed(0)}%`:'—'}</span></div>)}</div>:<div className="empty">Add crop cycles and matching market-price history to generate selling signals.</div>}<p className="note">Prices are compared only when units can be safely normalized. Quintal prices are converted to kg; incompatible units are not compared.</p></Card></>}

export function ForecastCenter({data}:{data:InsightData}){const crops=cropForecasts(data),herds=livestockBreakEven(data),warnings=weatherWarnings(data);return <><Card><h2>Operational weather warnings</h2>{warnings.map((x,i)=><div className="record" key={i}><span><b>{x}</b></span></div>)}</Card><div className="sectionHead"><div><small>ACTIVE CROPS</small><h2>Yield and revenue forecast</h2></div></div>{crops.length?crops.map(x=><Card key={x.cycleId}><div className="sectionHead"><div><h2>{x.crop}</h2><small>{x.confidence.replace('-',' ')} estimate</small></div><span className="pill">{x.projectedYield.toFixed(1)} {x.unit}</span></div><div className="metricGrid"><div><small>MARKET SIGNAL</small><strong>{x.marketPrice?`${money(x.marketPrice)}/${x.unit}`:'—'}</strong></div><div><small>PROJECTED REVENUE</small><strong>{money(x.projectedRevenue)}</strong></div><div><small>BREAK-EVEN PRICE</small><strong>{money(x.breakEvenPrice)}/{x.unit}</strong></div></div>{x.confidence==='insufficient'&&<p className="note">Record harvests or complete an earlier cycle of the same crop to improve this forecast.</p>}</Card>):<Card><div className="empty">No active crop cycles to forecast.</div></Card>}<div className="sectionHead"><div><small>GOATS & SHEEP</small><h2>Direct-cost recovery</h2></div></div>{herds.map(x=><Card key={x.herdId}><div className="sectionHead"><div><h2>{x.name}</h2><small>{x.recovered?'Direct costs recovered':'Recovery still required'}</small></div><span className={x.recovered?'pill good':'pill bad'}>{x.recovered?'Recovered':money(x.gap)}</span></div>{!x.recovered&&<p>{x.averagePrice?`${x.unitsNeeded.toFixed(1)} sale units required at the historical average price of ${money(x.averagePrice)}.`:'Record sales to calculate units required at the farm’s actual price.'}</p>}</Card>)}</>}

export function ManualWeather({data,act}:{data:InsightData;act:Action}){const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,f=new FormData(form),recordDate=String(f.get('date'));act(async()=>{const values={tempMin:Number(f.get('min')),tempMax:Number(f.get('max')),rainfallMm:Number(f.get('rain')),humidityPercent:Number(f.get('humidity'))};if(values.tempMax<values.tempMin)throw Error('Maximum temperature cannot be below minimum temperature.');if(values.rainfallMm<0||values.humidityPercent<0||values.humidityPercent>100)throw Error('Rainfall and humidity values are invalid.');const existing=await db.weatherLogs.where('date').equals(recordDate).first(),row=stamp({date:recordDate,...values,notes:String(f.get('notes')||''),source:'manual' as const,forecast:f.get('forecast')==='on'});if(existing)await db.weatherLogs.put({...row,id:existing.id,createdAt:existing.createdAt});else await db.weatherLogs.add(row)},'Weather record saved').then(saved=>{if(saved)form.reset()})};const archive=(row:WeatherLog)=>act(()=>db.weatherLogs.update(row.id,{deletedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}),'Weather record archived');return <div className="twoCol"><Card><h2>Manual weather record</h2><p className="note">Use this offline or when the weather service is unavailable. A record for the same date is updated.</p><form onSubmit={submit}><label>Date<input name="date" type="date" defaultValue={today()} required/></label><div className="formRow"><label>Minimum °C<input name="min" type="number" step=".1" required/></label><label>Maximum °C<input name="max" type="number" step=".1" required/></label></div><div className="formRow"><label>Rainfall mm<input name="rain" type="number" min="0" step=".1" required/></label><label>Humidity %<input name="humidity" type="number" min="0" max="100" step=".1" required/></label></div><label className="check"><input name="forecast" type="checkbox"/> This is a forecast</label><label>Notes<textarea name="notes"/></label><button className="primary" type="submit">Save weather</button></form></Card><Card><h2>Manual history</h2>{data.weatherLogs.filter(x=>x.source==='manual').sort((a,b)=>b.date.localeCompare(a.date)).map(x=><div className="record" key={x.id}><span><b>{date(x.date)} · {x.tempMin}–{x.tempMax}°C</b><small>{x.rainfallMm} mm · {x.humidityPercent}% humidity{x.forecast?' · forecast':''}</small></span><button className="danger small" onClick={()=>archive(x)}>Archive</button></div>)}</Card></div>}
