import { batchMetrics, cropMetrics, feedIssueCostPerUnit, herdMetrics, type FarmData, type Period } from './calculations';
import type { AdvancedData } from './advanced';
import type { Allocation, Worker } from './types';

export type ReportingData=FarmData&AdvancedData&{workers?:Worker[]};
export type LedgerEntry={id:string;date:string;direction:'in'|'out';source:string;description:string;amount:number;enterpriseId?:string;allocations?:Allocation[]};
export function unifiedLedger(data:ReportingData,period?:Period):LedgerEntry[]{const rows:LedgerEntry[]=[],inPeriod=(date:string)=>!period||(date>=period.from&&date<=period.to),add=(row:LedgerEntry)=>{if(inPeriod(row.date))rows.push(row)};
  data.expenses.forEach(x=>add({id:x.id,date:x.date,direction:'out',source:'Expense',description:x.category+(x.note?` · ${x.note}`:''),amount:x.amount,enterpriseId:x.enterpriseId,allocations:x.allocations}));
  data.otherIncome.forEach(x=>add({id:x.id,date:x.date,direction:'in',source:'Other income',description:x.source,amount:x.amount,enterpriseId:x.enterpriseId}));
  data.labourLogs.forEach(x=>add({id:x.id,date:x.date,direction:'out',source:'Labour',description:x.task,amount:x.amount,allocations:x.allocations}));
  data.batches.filter(x=>x.source==='purchased').forEach(x=>add({id:x.id,date:x.acquisitionDate,direction:'out',source:'Poultry acquisition',description:`${x.name} · ${x.initialCount} birds`,amount:x.acquisitionCost,enterpriseId:x.enterpriseId}));
  (data.additions||[]).filter(x=>x.cost).forEach(x=>{const batch=data.batches.find(b=>b.id===x.batchId);add({id:x.id,date:x.date,direction:'out',source:'Poultry addition',description:`${batch?.name||'Batch'} · ${x.count} birds`,amount:x.cost||0,enterpriseId:batch?.enterpriseId})});
  data.healthRecords.forEach(x=>{const batch=data.batches.find(b=>b.id===x.batchId);add({id:x.id,date:x.date,direction:'out',source:'Poultry health',description:`${batch?.name||'Batch'} · ${x.type}`,amount:x.cost,enterpriseId:batch?.enterpriseId})});
  data.eggSales.forEach(x=>add({id:x.id,date:x.date,direction:'in',source:'Egg sale',description:`${x.quantity} eggs · ${x.buyer}`,amount:x.total,enterpriseId:x.enterpriseId}));
  data.birdSales.forEach(x=>add({id:x.id,date:x.date,direction:'in',source:'Bird sale',description:`${x.count} birds · ${x.buyer}`,amount:x.total,enterpriseId:x.enterpriseId}));
  data.feedPurchases.forEach(x=>add({id:x.id,date:x.date,direction:'out',source:'Feed purchase',description:`${data.feedTypes.find(t=>t.id===x.feedTypeId)?.name||'Feed'} · ${x.quantity}`,amount:x.totalCost,allocations:x.allocations}));
  data.feedInputs.forEach(x=>add({id:x.id,date:x.date,direction:'out',source:'Feed production input',description:`${data.feedUnits.find(u=>u.id===x.unitId)?.name||'Unit'} · ${x.inputType}`,amount:x.amount}));
  data.herds.forEach(x=>add({id:x.id,date:x.acquisitionDate,direction:'out',source:'Herd acquisition',description:`${x.name} · ${x.initialCount} head`,amount:x.acquisitionCost,enterpriseId:x.enterpriseId}));
  (data.herdAdditions||[]).filter(x=>x.cost).forEach(x=>{const herd=data.herds.find(h=>h.id===x.herdId);add({id:x.id,date:x.date,direction:'out',source:'Herd addition',description:`${herd?.name||'Herd'} · ${x.count} head`,amount:x.cost||0,enterpriseId:herd?.enterpriseId})});
  data.herdHealth.forEach(x=>{const herd=data.herds.find(h=>h.id===x.herdId);add({id:x.id,date:x.date,direction:'out',source:'Herd health',description:`${herd?.name||'Herd'} · ${x.type}`,amount:x.cost,enterpriseId:herd?.enterpriseId})});
  data.herdSales.forEach(x=>add({id:x.id,date:x.date,direction:'in',source:`Herd ${x.saleType} sale`,description:`${x.quantity} ${x.unit} · ${x.buyer}`,amount:x.total,enterpriseId:x.enterpriseId}));
  data.cropInputs.forEach(x=>{const cycle=data.cropCycles.find(c=>c.id===x.cycleId);add({id:x.id,date:x.date,direction:'out',source:'Crop input',description:`${cycle?.crop||'Crop'} · ${x.inputType}`,amount:x.amount,enterpriseId:cycle?.enterpriseId})});
  data.cropSales.forEach(x=>add({id:x.id,date:x.date,direction:'in',source:'Crop sale',description:`${data.cropCycles.find(c=>c.id===x.cycleId)?.crop||'Crop'} · ${x.quantity} ${x.unit} · ${x.buyer}`,amount:x.total,enterpriseId:x.enterpriseId}));
  return rows.sort((a,b)=>b.date.localeCompare(a.date)||a.source.localeCompare(b.source));
}

export function detailedPerformance(data:ReportingData){return {poultry:data.batches.map(batch=>({batch:batch.name,enterpriseId:batch.enterpriseId,...batchMetrics(batch,data)})),herds:data.herds.map(herd=>({herd:herd.name,enterpriseId:herd.enterpriseId,...herdMetrics(herd,data)})),crops:data.cropCycles.map(cycle=>({crop:cycle.crop,cycleId:cycle.id,enterpriseId:cycle.enterpriseId,status:cycle.status,areaAcres:cycle.areaAcres,...cropMetrics(cycle,data)}))}}

export type MLRow={timestamp:string;date:string;enterprise_id:string;entity_type:string;entity_id:string;event_type:string;metric:string;value:number|string;unit:string;context:string};
export function seasonForDate(date:string){const month=Number(date.slice(5,7));return month>=6&&month<=10?'Kharif':month===11||month===12||month<=3?'Rabi':'summer'}
export function buildMLRows(data:ReportingData):MLRow[]{const rows:MLRow[]=[],add=(date:string,enterprise:string,entity:string,id:string,event:string,metric:string,value:number|string,unit:string,context:unknown={})=>rows.push({timestamp:`${date}T00:00:00`,date,enterprise_id:enterprise||'',entity_type:entity,entity_id:id,event_type:event,metric,value,unit,context:JSON.stringify(context)}),batchEnterprise=(id:string|undefined)=>data.batches.find(x=>x.id===id)?.enterpriseId||'',herdEnterprise=(id:string)=>data.herds.find(x=>x.id===id)?.enterpriseId||'',cropEnterprise=(id:string)=>data.cropCycles.find(x=>x.id===id)?.enterpriseId||'';
  data.expenses.forEach(x=>add(x.date,x.enterpriseId||'','finance',x.id,'expense','amount',x.amount,'INR',{category:x.category,isCapital:x.isCapital,allocations:x.allocations}));data.otherIncome.forEach(x=>add(x.date,x.enterpriseId,'finance',x.id,'income','amount',x.amount,'INR',{source:x.source}));data.labourLogs.forEach(x=>{add(x.date,'','labour',x.id,'work','amount',x.amount,'INR',{task:x.task,workerId:x.workerId,paid:x.paid,allocations:x.allocations});add(x.date,'','labour',x.id,'work','quantity',x.quantity,'work-unit',{task:x.task})});
  data.batches.forEach(x=>add(x.acquisitionDate,x.enterpriseId,'poultry',x.id,'acquisition','initial_count',x.initialCount,'head',{breed:x.breed,purpose:x.purpose,source:x.source,stage:x.stage,ageAtAcquisitionDays:x.ageAtAcquisitionDays}));data.eggDispositions.forEach(x=>add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId||x.id,'egg_disposition','quantity',x.quantity,'piece',{type:x.type,linkedBatchId:x.linkedBatchId}));data.layingCountLogs.forEach(x=>add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'laying_count','hens',x.layingHenCount,'head'));
  data.additions.forEach(x=>{add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'addition','count',x.count,'head');if(x.cost!=null)add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'addition','cost',x.cost,'INR')});data.mortalities.forEach(x=>add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'mortality','count',x.countLost,'head',{cause:x.cause}));data.healthRecords.forEach(x=>add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'health','cost',x.cost,'INR',{type:x.type,nextDueDate:x.nextDueDate}));data.eggProduction.forEach(x=>add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId||x.id,'production','eggs',x.eggsCollected,'piece'));data.eggSales.forEach(x=>{add(x.date,x.enterpriseId,'poultry',x.batchId||x.id,'sale','quantity',x.quantity,'piece',{buyer:x.buyer});add(x.date,x.enterpriseId,'poultry',x.batchId||x.id,'sale','price',x.pricePerEgg,'INR/piece')});data.birdSales.forEach(x=>{add(x.date,x.enterpriseId,'poultry',x.batchId,'sale','count',x.count,'head',{saleType:x.saleType});if(x.totalWeightKg!=null)add(x.date,x.enterpriseId,'poultry',x.batchId,'sale','weight',x.totalWeightKg,'kg')});data.poultryWeights.forEach(x=>{add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'weight','total_weight',x.totalWeightKg,'kg');add(x.date,batchEnterprise(x.batchId),'poultry',x.batchId,'weight','bird_count',x.birdCount,'head')});
  data.feedInputs.forEach(x=>add(x.date,'','feed',x.unitId,'production_input','cost',x.amount,'INR',{inputType:x.inputType,isCapital:x.isCapital}));
  data.feedPurchases.forEach(x=>{add(x.date,'','feed',x.feedTypeId,'purchase','quantity',x.quantity,data.feedTypes.find(t=>t.id===x.feedTypeId)?.unit||'kg',{supplier:x.supplier,lot:x.lotNumber,allocations:x.allocations});add(x.date,'','feed',x.feedTypeId,'purchase','cost',x.totalCost,'INR')});data.feedHarvests.forEach(x=>add(x.date,'','feed',x.unitId,'harvest','quantity',x.quantity,x.unit,{allocations:x.allocations}));data.feedConsumption.forEach(x=>{const enterprise=x.enterpriseId||herdEnterprise(x.herdId||'')||batchEnterprise(x.batchId);add(x.date,enterprise,'feed',x.feedTypeId,'consumption','quantity',x.quantity,data.feedTypes.find(t=>t.id===x.feedTypeId)?.unit||'kg',{batchId:x.batchId,herdId:x.herdId,cost:feedIssueCostPerUnit(x,data)})});
  data.animals.forEach(x=>{const eventDate=x.birthDate||x.acquisitionDate;if(eventDate)add(eventDate,herdEnterprise(x.herdId),'animal',x.id,'registration','status',x.status,'category',{tag:x.tag,species:x.species,sex:x.sex,breed:x.breed,damId:x.damId,sireId:x.sireId})});
  data.herdAdditions.forEach(x=>{add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,x.eventType,'count',x.count,'head',{born:x.born,survived:x.survived});if(x.cost!=null)add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,x.eventType,'cost',x.cost,'INR')});data.breedingEvents.forEach(x=>{add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,'breeding','born',x.numberBorn,'head',{damId:x.damId});add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,'breeding','survived',x.numberSurvived,'head')});data.herdMortalities.forEach(x=>add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,'mortality','count',x.countLost,'head',{cause:x.cause,animalId:x.animalId}));data.herdHealth.forEach(x=>add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,'health','cost',x.cost,'INR',{type:x.type,nextDueDate:x.nextDueDate}));data.weightLogs.forEach(x=>add(x.date,herdEnterprise(x.herdId),'herd',x.herdId,'weight',x.weightBasis==='average'?'average_weight':'total_weight',x.weightKg,'kg',{animalCount:x.animalCount}));data.herdSales.forEach(x=>{add(x.date,x.enterpriseId,'herd',x.herdId,'sale','quantity',x.quantity,x.unit,{saleType:x.saleType,buyer:x.buyer,animalId:x.animalId});add(x.date,x.enterpriseId,'herd',x.herdId,'sale','price',x.unitPrice,`INR/${x.unit}`)});
  data.plotCycles.forEach(x=>add(x.startDate,x.enterpriseId,'land',x.id,'rotation_start','area',data.landPlots.find(p=>p.id===x.plotId)?.areaAcres||0,'acre',{plotId:x.plotId,cropOrUse:x.cropOrUse,seasonYear:x.seasonYear,endDate:x.endDate,season:seasonForDate(x.startDate)}));
  data.cropCycles.forEach(x=>add(x.sowingDate,x.enterpriseId,'crop',x.id,'sowing','area',x.areaAcres,'acre',{crop:x.crop,type:x.type,plotId:x.plotId,expectedHarvest:x.expectedHarvest,season:seasonForDate(x.sowingDate)}));
  data.cropInputs.forEach(x=>add(x.date,cropEnterprise(x.cycleId),'crop',x.cycleId,'input','cost',x.amount,'INR',{inputType:x.inputType,isCapital:x.isCapital}));data.cropHarvests.forEach(x=>add(x.date,cropEnterprise(x.cycleId),'crop',x.cycleId,'harvest','quantity',x.quantity,x.unit));data.cropSales.forEach(x=>{add(x.date,x.enterpriseId,'crop',x.cycleId,'sale','quantity',x.quantity,x.unit,{buyer:x.buyer});add(x.date,x.enterpriseId,'crop',x.cycleId,'sale','price',x.unitPrice,`INR/${x.unit}`)});
  data.weatherLogs.forEach(x=>{const context={source:x.source,season:seasonForDate(x.date)};add(x.date,'','weather',x.id,x.forecast?'forecast':'observation','temp_min',x.tempMin,'celsius',context);add(x.date,'','weather',x.id,x.forecast?'forecast':'observation','temp_max',x.tempMax,'celsius',context);add(x.date,'','weather',x.id,x.forecast?'forecast':'observation','rainfall',x.rainfallMm,'mm',context);add(x.date,'','weather',x.id,x.forecast?'forecast':'observation','humidity',x.humidityPercent,'percent',context)});data.marketPrices.forEach(x=>{add(x.date,'','market',x.id,'reference','min_price',x.minPrice,x.unit,{commodity:x.commodity,market:x.market});add(x.date,'','market',x.id,'reference','max_price',x.maxPrice,x.unit,{commodity:x.commodity,market:x.market});add(x.date,'','market',x.id,'reference','modal_price',x.modalPrice,x.unit,{commodity:x.commodity,market:x.market});if(x.arrivalQuantity!=null)add(x.date,'','market',x.id,'reference','arrival_quantity',x.arrivalQuantity,x.unit,{commodity:x.commodity,market:x.market})});return rows.sort((a,b)=>a.date.localeCompare(b.date)||a.entity_type.localeCompare(b.entity_type));
}
const quote=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;
export function mlCsv(data:ReportingData){const rows=buildMLRows(data),headers=Object.keys(rows[0]||{timestamp:'',date:'',enterprise_id:'',entity_type:'',entity_id:'',event_type:'',metric:'',value:'',unit:'',context:''}) as (keyof MLRow)[];return [headers.map(quote).join(','),...rows.map(row=>headers.map(key=>quote(row[key])).join(','))].join('\r\n')}


