export type ID = string;
export type EnterpriseType = 'livestock' | 'commercial-crop' | 'feed-crop';
export type Allocation = { enterpriseId: ID; percent: number };
export type BaseRecord = { id: ID; createdAt: string; updatedAt: string; deletedAt?: string };
export type Enterprise = BaseRecord & { name: string; type: EnterpriseType; active: boolean };
export type Expense = BaseRecord & { date: string; category: 'feed' | 'utilities' | 'infrastructure' | 'equipment' | 'transport' | 'misc'; amount: number; isCapital: boolean; usefulLifeMonths?: number; enterpriseId?: ID; batchId?: ID; plotCycleId?: ID; allocations?: Allocation[]; allocationDriver?: 'manual'|'animal-days'|'area'|'labour-quantity'|'harvest-share'; note?: string };
export type OtherIncome = BaseRecord & { date: string; source: string; amount: number; enterpriseId: ID; note?: string };
export type Worker = BaseRecord & { name: string; wageType: 'daily' | 'monthly' | 'piece'; rate: number; phone?: string; active: boolean };
export type LabourLog = BaseRecord & { workerId: ID; date: string; task: string; quantity: number; amount: number; allocations: Allocation[]; batchId?: ID; paid: boolean };
export type Batch = BaseRecord & { name: string; breed: string; purpose: 'layer' | 'meat' | 'dual'; source: 'purchased' | 'hatched'; acquisitionDate: string; stage: 'chick' | 'grower' | 'adult'; ageAtAcquisitionDays: number; initialCount: number; acquisitionCost: number; expectedLayStart?: string; targetMeatAgeDays?: number; notes?: string; parentDispositionId?: ID; eggsSet?: number; hatchSuccessCount?: number; enterpriseId: ID; active?: boolean; closedDate?: string };
export type BatchAddition = BaseRecord & { batchId: ID; date: string; count: number; cost?: number; note?: string };
export type MortalityEvent = BaseRecord & { batchId: ID; date: string; countLost: number; cause: 'disease' | 'predator' | 'heat' | 'injury' | 'unknown'; note?: string };
export type HealthRecord = BaseRecord & { batchId: ID; date: string; type: string; quantity?: number; cost: number; nextDueDate?: string; note?: string };
export type EggProduction = BaseRecord & { date: string; batchId?: ID; eggsCollected: number };
export type EggDisposition = BaseRecord & { date: string; batchId?: ID; quantity: number; type: 'sold' | 'home-use' | 'set-for-hatching' | 'broken-spoiled'; linkedSaleId?: ID; linkedBatchId?: ID };
export type EggSale = BaseRecord & { date: string; batchId?: ID; quantity: number; pricePerEgg: number; total: number; buyer: string; dispositionId: ID; enterpriseId: ID };
export type BirdSale = BaseRecord & { date: string; batchId: ID; count: number; saleType: 'live' | 'dressed'; totalWeightKg?: number; pricingBasis: 'kg' | 'bird'; unitPrice: number; total: number; buyer: string; enterpriseId: ID };
export type FeedType = BaseRecord & { name: string; category: 'energy'|'protein'|'greens'|'mineral'|'complete'; source: 'purchased'|'home-grown'; unit: 'kg'|'litre'; cpPercent?: number; energyKcalKg?: number; calciumPercent?: number; costPerUnit?: number; minInclusionPercent?: number; maxInclusionPercent?: number; active: boolean };
export type FeedPurchase = BaseRecord & { date: string; feedTypeId: ID; quantity: number; totalCost: number; supplier: string; lotNumber?: string; expiryDate?: string; allocations: Allocation[]; batchId?: ID; herdId?: ID };
export type FeedProductionUnit = BaseRecord & { name: string; sourceType: 'azolla-pit'|'bsf-bin'|'mulberry-strip'|'maize-plot'|'other'; feedTypeId?: ID; plotCycleId?: ID; cropCycleId?:ID; active: boolean };
export type FeedProductionInput = BaseRecord & { unitId: ID; date: string; inputType: 'seed-spawn'|'setup-material'|'labour'|'water-electricity'|'fertiliser'|'other'; amount: number; isCapital: boolean };
export type FeedHarvest = BaseRecord & { unitId: ID; date: string; quantity: number; unit: 'kg'|'litre'; allocations: Allocation[] };
export type FeedConsumption = BaseRecord & { date: string; feedTypeId: ID; quantity: number; batchId?: ID; herdId?: ID; enterpriseId: ID; feedPurchaseId?:ID; issueGroupId?:ID };
export type LandPlot = BaseRecord & { name: string; areaAcres: number; notes?: string; active: boolean };
export type PlotCycle = BaseRecord & { plotId: ID; seasonYear: string; cropOrUse: string; enterpriseId: ID; startDate: string; endDate?: string };
export type Herd = BaseRecord & { name: string; species: 'goat'|'sheep'; breed: string; purpose: 'meat'|'milk'|'breeding'; acquisitionDate: string; initialCount: number; acquisitionCost: number; enterpriseId: ID; notes?: string; active?: boolean; closedDate?: string };
export type Animal = BaseRecord & { herdId:ID; tag:string; species:'goat'|'sheep'; sex:'female'|'male'; breed:string; birthDate?:string; acquisitionDate?:string; damId?:ID; sireId?:ID; status:'active'|'sold'|'died'; notes?:string };
export type BreedingEvent = BaseRecord & { herdId:ID; damId?:ID; date:string; numberBorn:number; numberSurvived:number; followUpDate?:string; note?:string };
export type HerdAddition = BaseRecord & { herdId: ID; date: string; count: number; eventType: 'purchase'|'birth'; cost?: number; born?: number; survived?: number; note?: string };
export type HerdMortality = BaseRecord & { herdId: ID; animalId?: ID; date: string; countLost: number; cause: 'disease'|'predator'|'heat'|'injury'|'unknown'; note?: string };
export type HerdHealth = BaseRecord & { herdId: ID; date: string; type: string; cost: number; nextDueDate?: string; note?: string };
export type WeightLog = BaseRecord & { herdId: ID; date: string; weightKg: number; animalCount: number; weightBasis?:'total'|'average' };
export type PoultryWeightLog = BaseRecord & { batchId: ID; date: string; totalWeightKg: number; birdCount: number };
export type LayingCountLog = BaseRecord & { batchId: ID; date: string; layingHenCount: number };
export type HerdSale = BaseRecord & { herdId: ID; animalId?: ID; enterpriseId: ID; date: string; count: number; saleType: 'live'|'meat'|'milk'; quantity: number; unit: 'kg'|'litre'|'head'; unitPrice: number; total: number; buyer: string };
export type CropCycle = BaseRecord & { plotId: ID; crop: string; enterpriseId: ID; type: 'commercial'|'feed'; sowingDate: string; expectedHarvest?: string; completedDate?: string; areaAcres: number; status: 'planned'|'active'|'harvesting'|'complete' };
export type CropOperationInput = BaseRecord & { cycleId: ID; date: string; inputType: 'land-prep'|'seed-sapling'|'fertiliser'|'pesticide'|'irrigation'|'labour'|'other'; amount: number; isCapital: boolean };
export type CropHarvest = BaseRecord & { cycleId: ID; date: string; quantity: number; unit: 'kg'|'bunch'|'piece'; feedHarvestId?:ID };
export type CropSale = BaseRecord & { cycleId: ID; enterpriseId: ID; date: string; quantity: number; unit: 'kg'|'bunch'|'piece'; unitPrice: number; total: number; buyer: string };
export type WeatherLog = BaseRecord & { date: string; tempMin: number; tempMax: number; rainfallMm: number; humidityPercent: number; notes?: string; source: 'manual'|'open-meteo'; forecast: boolean };
export type MarketPrice = BaseRecord & { date: string; commodity: string; variety?: string; market: string; minPrice: number; maxPrice: number; modalPrice: number; arrivalQuantity?: number; unit: string; source: 'manual'|'data.gov.in' };
export type AppSetting = { key: string; value: string };

export const now = () => new Date().toISOString();
export const localDate = (value = new Date()) => `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;
export const id = () => crypto.randomUUID();
export const roundMoney = (value: number) => Math.round((value + Math.sign(value) * Number.EPSILON) * 100) / 100;
export const stamp = <T extends object>(data: T): T & BaseRecord => ({ ...data, id: id(), createdAt: now(), updatedAt: now() });
